name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: |
          echo "helloworld"
          echo "worldhello"
      - name: goodbye
        run: echo "bye"
